/*
 * NghiepvuPnl.java
 *
 * Created on August 27, 2006, 11:09 AM
 */
package org.childcare.buss.panel;

/**
 *
 * @author Nguyễn Anh Minh
 * E-mail : anhminhnguyen@gmail.com
 * Skype: nguyen.anhminh
 */
public class NghiepvuPnl extends javax.swing.JPanel {

    /** Creates new form NghiepvuPnl */
    public NghiepvuPnl() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlTrai = new javax.swing.JPanel();
        scpTaikhoan = new javax.swing.JScrollPane();
        lstTaikhoan = new javax.swing.JList();
        btnThem = new javax.swing.JButton();
        btnMacdinh = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        pnlPhai = new javax.swing.JPanel();
        lblTieude = new javax.swing.JLabel();
        lblTaikhoan = new javax.swing.JLabel();
        txtTaikhoan = new javax.swing.JTextField();
        pnlXacthuc = new javax.swing.JPanel();
        lblThongbao = new javax.swing.JLabel();
        lblHoten = new javax.swing.JLabel();
        txtHoten = new javax.swing.JTextField();
        lblTochuc = new javax.swing.JLabel();
        txtTochuc = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblPhanhoi = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPhanhoi = new javax.swing.JTextField();
        chkChuky = new javax.swing.JCheckBox();
        txtChuky = new javax.swing.JTextField();
        btnChuky = new javax.swing.JButton();
        chkHTML = new javax.swing.JCheckBox();
        pnlDieukhien = new javax.swing.JPanel();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnTrogiup = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        pnlTrai.setLayout(new java.awt.GridBagLayout());

        scpTaikhoan.setViewportView(lstTaikhoan);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        pnlTrai.add(scpTaikhoan, gridBagConstraints);

        btnThem.setText("Tạo tài khoản");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        pnlTrai.add(btnThem, gridBagConstraints);

        btnMacdinh.setText("Thiết lập mặc định");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        pnlTrai.add(btnMacdinh, gridBagConstraints);

        btnXoa.setText("Xoá tài khoản");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        pnlTrai.add(btnXoa, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        add(pnlTrai, gridBagConstraints);

        pnlPhai.setLayout(new java.awt.GridBagLayout());

        lblTieude.setFont(new java.awt.Font("Tahoma", 0, 16));
        lblTieude.setForeground(new java.awt.Color(0, 0, 255));
        lblTieude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieude.setText("Quản Trị Tài Khoản");
        lblTieude.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        pnlPhai.add(lblTieude, gridBagConstraints);

        lblTaikhoan.setText("Tài khoản:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        pnlPhai.add(lblTaikhoan, gridBagConstraints);

        txtTaikhoan.setBackground(new java.awt.Color(233, 229, 214));
        txtTaikhoan.setText("anhminhnguyen@gmail.com");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        pnlPhai.add(txtTaikhoan, gridBagConstraints);

        pnlXacthuc.setBorder(javax.swing.BorderFactory.createTitledBorder("Xác thực thông tin"));
        pnlXacthuc.setLayout(new java.awt.GridBagLayout());

        lblThongbao.setText("<html>Thông tin xác thực đối với từng tài khoản, những thông tin này sẽ đi kèm trong nội dung e-mail của bạn.</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        pnlXacthuc.add(lblThongbao, gridBagConstraints);

        lblHoten.setText("Họ tên:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        pnlXacthuc.add(lblHoten, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        pnlXacthuc.add(txtHoten, gridBagConstraints);

        lblTochuc.setText("Tổ chức:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        pnlXacthuc.add(lblTochuc, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        pnlXacthuc.add(txtTochuc, gridBagConstraints);

        lblEmail.setText("E-mail:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        pnlXacthuc.add(lblEmail, gridBagConstraints);

        lblPhanhoi.setText("E-mail phản hồi:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        pnlXacthuc.add(lblPhanhoi, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        pnlXacthuc.add(txtEmail, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        pnlXacthuc.add(txtPhanhoi, gridBagConstraints);

        chkChuky.setText("Chữ ký đính kèm");
        chkChuky.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkChuky.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        pnlXacthuc.add(chkChuky, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        pnlXacthuc.add(txtChuky, gridBagConstraints);

        btnChuky.setText("Chọn...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 5);
        pnlXacthuc.add(btnChuky, gridBagConstraints);

        chkHTML.setText("Chế độ soạn thảo HTML");
        chkHTML.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkHTML.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        pnlXacthuc.add(chkHTML, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 3, 3);
        pnlPhai.add(pnlXacthuc, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 1.0;
        add(pnlPhai, gridBagConstraints);

        pnlDieukhien.setLayout(new java.awt.GridBagLayout());

        btnLuu.setText("Lưu");
        btnLuu.setMaximumSize(new java.awt.Dimension(72, 23));
        btnLuu.setMinimumSize(new java.awt.Dimension(72, 23));
        btnLuu.setPreferredSize(new java.awt.Dimension(72, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        pnlDieukhien.add(btnLuu, gridBagConstraints);

        btnHuy.setText("Huỷ");
        btnHuy.setMaximumSize(new java.awt.Dimension(72, 23));
        btnHuy.setMinimumSize(new java.awt.Dimension(72, 23));
        btnHuy.setPreferredSize(new java.awt.Dimension(72, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        pnlDieukhien.add(btnHuy, gridBagConstraints);

        btnTrogiup.setText("Trợ giúp");
        btnTrogiup.setMaximumSize(new java.awt.Dimension(72, 23));
        btnTrogiup.setMinimumSize(new java.awt.Dimension(72, 23));
        btnTrogiup.setPreferredSize(new java.awt.Dimension(72, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        pnlDieukhien.add(btnTrogiup, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(pnlDieukhien, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuky;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnMacdinh;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTrogiup;
    private javax.swing.JButton btnXoa;
    private javax.swing.JCheckBox chkChuky;
    private javax.swing.JCheckBox chkHTML;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblHoten;
    private javax.swing.JLabel lblPhanhoi;
    private javax.swing.JLabel lblTaikhoan;
    private javax.swing.JLabel lblThongbao;
    private javax.swing.JLabel lblTieude;
    private javax.swing.JLabel lblTochuc;
    private javax.swing.JList lstTaikhoan;
    private javax.swing.JPanel pnlDieukhien;
    private javax.swing.JPanel pnlPhai;
    private javax.swing.JPanel pnlTrai;
    private javax.swing.JPanel pnlXacthuc;
    private javax.swing.JScrollPane scpTaikhoan;
    private javax.swing.JTextField txtChuky;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtPhanhoi;
    private javax.swing.JTextField txtTaikhoan;
    private javax.swing.JTextField txtTochuc;
    // End of variables declaration//GEN-END:variables
}
