/*
 * DanhmucPnl.java
 *
 * Created on August 24, 2006, 1:47 AM
 */

package org.childcare.buss.panel;

/**
 *
 * @author Nguy?n Anh Minh
 * E-mail : anhminhnguyen@gmail.com
 * Skype: nguyen.anhminh
 */
public class DanhmucPnl extends javax.swing.JPanel {
    
    /**
     * Creates new form DanhmucPnl
     */
    public DanhmucPnl() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        scpDanhmuc = new javax.swing.JScrollPane();
        tblDanhmuc = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        tblDanhmuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpDanhmuc.setViewportView(tblDanhmuc);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(scpDanhmuc, gridBagConstraints);

        btnThem.setText("Th\u00eam");
        btnThem.setMaximumSize(new java.awt.Dimension(60, 23));
        btnThem.setMinimumSize(new java.awt.Dimension(60, 23));
        btnThem.setPreferredSize(new java.awt.Dimension(60, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        add(btnThem, gridBagConstraints);

        btnSua.setText("S\u1eeda");
        btnSua.setMaximumSize(new java.awt.Dimension(60, 23));
        btnSua.setMinimumSize(new java.awt.Dimension(60, 23));
        btnSua.setPreferredSize(new java.awt.Dimension(60, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        add(btnSua, gridBagConstraints);

        btnXoa.setText("Xo\u00e1");
        btnXoa.setMaximumSize(new java.awt.Dimension(60, 23));
        btnXoa.setMinimumSize(new java.awt.Dimension(60, 23));
        btnXoa.setPreferredSize(new java.awt.Dimension(60, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        add(btnXoa, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JScrollPane scpDanhmuc;
    private javax.swing.JTable tblDanhmuc;
    // End of variables declaration//GEN-END:variables
    
}
